name: Backend Portfolio CI/CD

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy on render.
    runs-on: ubuntu-latest

    steps: 
      - name: Deploy to production
        uses: render-examples/github-actions-deploy@main
        with:
          render_account_id: ${{ secrets.RENDER_ACCOUNT_ID }}
          render_token: ${{ secrets.RENDER_TOKEN }}
          service-id: ${{ secrets.SERVICE_ID }}